version: '3.8'
services:
  web-client:
    depends_on:
    - web-server
    restart: always
    build:
      target: client-dev
      args:
      - SERVER_HOST_NAME=web-server
      - SERVER_PORT=${SERVER_PORT}
    environment:
    - BACKEND_API=web-server:${SERVER_PORT}/api
    - WDS_SOCKET_PORT=8080
    ports:
    - 3000:3000
    volumes:
    - ./frontend/src:/usr/src/app/src
  web-server:
    build:
      target: server-dev
    volumes:
    - ./backend/src/server.js:/usr/src/app/server.js