version: '3.8'
services:
  web-client:
    depends_on:
    - web-server
    restart: always
    build:
      target: client-dev
    environment:
    - BACKEND_API=web-server:${EXPRESS_PORT}/api
    - WDS_SOCKET_PORT=8080
    ports:
    - 8080:3000
    volumes:
    - ./frontend/src:/usr/src/app/src
  web-server:
    build:
      target: server-dev
    volumes:
    - ./backend/src/server.js:/usr/src/app/server.js