version: '3.8'
services:
  web-server:
    depends_on:
    - database
    restart: always
    image: erikja/synonyms-server:0.1.1
    build:
      target: server-prod
      args:
      - PORT=${SERVER_PORT}
    environment:
    - SERVER_PORT=${SERVER_PORT}
    - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    - MYSQL_HOST_NAME=database
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - SERVER_USER=${SERVER_USER}
    - SERVER_PASSWORD_FILE=/run/secrets/server_password
    ports:
    - 8443:${SERVER_PORT}
    secrets:
    - db_password
    - server_password
  database:
    image: mysql:8.1.0
    environment:
    - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    - MYSQL_DATABASE=synonyms
    - MYSQL_RANDOM_ROOT_PASSWORD=y
    expose:
    - ${MYSQL_TCP_PORT}
    secrets:
    - db_password
    volumes:
    - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    - db:/var/lib/mysql
volumes:
 db:
secrets:
  db_password:
    file: ./db_password
  server_password:
    file: ./server_password