version: '3.8'
services:
  web-client:
    depends_on:
    - web-server
    restart: always
    build:
      context: frontend
      target: client-dev
    environment:
    - BACKEND_API=web-server:${EXPRESS_PORT}/api
    - WDS_SOCKET_PORT=8080
    ports:
    - 8080:3000
    volumes:
    - ./frontend/src:/usr/src/app/src
  web-server:
    depends_on:
    - database
    restart: always
    build:
      context: backend
      args:
      - PORT=${EXPRESS_PORT}
    environment:
    - EXPRESS_PORT=${EXPRESS_PORT}
    - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_HOST_NAME=database
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
    - 3000:${EXPRESS_PORT}
    volumes:
    - ./backend/src/server.js:/usr/src/app/server.js
  database:
    image: mysql:8.1.0
    environment:
    - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=synonyms
    - MYSQL_RANDOM_ROOT_PASSWORD=y
    expose:
    - ${MYSQL_TCP_PORT}
    volumes:
    - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    - db:/var/lib/mysql
volumes:
 db: