---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    solution: synonyms
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      solution: synonyms
      app: database
  template:
    metadata:
      labels:
        solution: synonyms
        app: database
    spec:
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.azure.com/role
                operator: In
                values:
                - agent
      containers:
      - name: database
        image: mysql:8.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_TCP_PORT
          value: {{ .Values.database.port | quote }}
        - name: MYSQL_USER
          value: {{ .Values.database.user }}
        - name: MYSQL_PASSWORD_FILE
          value: /run/secrets/db_password
        - name: MYSQL_DATABASE
          value: {{ .Values.database.database }}
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "y"
        ports:
        - name: https-database
          containerPort: 3306
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
        - name: database
          mountPath: /var/lib/mysql
        - name: password
          mountPath: /run/secrets/db_password
          subPath: db_password
      volumes:
      - name: db-init
        configMap:
          name: database
      - name: database
        persistentVolumeClaim:
          claimName: database
      - name: password
        secret:
          secretName: database
