apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    solution: synonyms
    app: database
  ports:
  - name: database-svc
    protocol: TCP
    port: 3306
    targetPort: https-database
