---
apiVersion: v1
kind: Service
metadata:
  labels:
    solution: synonyms
    app: webserver
  name: webserver
spec:
  type: LoadBalancer
  ports:
  - name: webserver-svc
    protocol: TCP
    port: 443
    targetPort: https-webserver
  selector:
    solution: synonyms
    app: webserver

